image: golang:1
stages:
  - build

default:
  tags:
    - docker
    - linux

.build:
  stage: build
  variables:
    VERSION: $CI_COMMIT_BRANCH.$CI_PIPELINE_IID
  script:
    - make release
  artifacts:
    paths:
      - ./bin
    expire_in: 30 days

build_develop:
  extends: .build
  artifacts:
    paths:
      - ./bin
    expire_in: 24 hours
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^develop$/'


build_release:
  stage: build
  image:
    name: goreleaser/goreleaser:v1.1.0
    entrypoint: ['']
  before_script:
    - apk add gnupg
    - gpg --import $GPG_SIGN_KEY
  script:
    - goreleaser release --rm-dist --skip-announce --skip-publish
  artifacts:
    name: "release-files"
    paths:
      - ./dist/*.zip
      - ./dist/*_SHA256SUMS
      - ./dist/*_SHA256SUMS.sig
    expire_in: 1 week
  only:
    - tags
